"""subscriptions table

Revision ID: 291fcdd075e
Revises: 5882233158f
Create Date: 2014-09-30 02:06:06.701055

"""

# revision identifiers, used by Alembic.
revision = '291fcdd075e'
down_revision = '5882233158f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('username', sa.Unicode(), nullable=True),
    sa.Column('upcoming_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['upcoming_id'], ['upcomings.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['username'], ['users.username'], onupdate='CASCADE', ondelete='CASCADE')
    )
    op.alter_column('upcomings', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upcomings', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('subscriptions')
    ### end Alembic commands ###
