"""tsvector for upcomings

Revision ID: 4187b6e458f
Revises: 291fcdd075e
Create Date: 2014-09-30 17:17:30.442712

"""

# revision identifiers, used by Alembic.
revision = '4187b6e458f'
down_revision = '291fcdd075e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy_searchable import sync_trigger
from sqlalchemy_utils.types import TSVectorType


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upcomings', sa.Column('search_vector', TSVectorType(),
                                         nullable=True))

    conn = op.get_bind()
    sync_trigger(conn, 'upcomings', 'search_vector', ['name', 'description'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upcomings', 'search_vector')
    ### end Alembic commands ###
