"""upcoming url

Revision ID: 8c313357d2
Revises: 4187b6e458f
Create Date: 2014-10-02 19:39:21.470368

"""

# revision identifiers, used by Alembic.
revision = '8c313357d2'
down_revision = '4187b6e458f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upcomings', sa.Column('website', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upcomings', 'website')
    ### end Alembic commands ###
